theme: jekyll-theme-cayman
title: Grégoire Hébert - blog
description: Senior Developer & Trainer @ Les-tilleuls.coop
email: gregoire@les-tilleuls.coop
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gregoirehebert.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "gheb_dev"
github_username:  "gregoirehebert"
show_downloads: [false]
google_analytics: "UA-45648310-1"
